### ISSUE TITLE
Leather belt..?

### ISSUE THREAD

**Issue by SilkenStrand** [Kiyaku/SeriousRemnants#1]
You need a leather belt for a saw, and a saw for the bark for the tanned leather for the belt? And I noticed survivalist tanned leather but it couldn't be cut into strips.. Am I missing something? 

Anyway, fun pack, although I froze to death my first night and had quite a time trying to get back to my stuff with all the enemies while having only 3 hearts haha

**Comment by SeriousCreeper** [comment]
Not missing anything, it's a derp on my end heh. I'm gonna upload a new version very soon. 

Thanks, glad you are liking it! Yeah dying and respawning in the middle of the night is the worst if that happens xD I might add a structure that spawns at the players spawn when creating a world, that has some lights.

**Comment by SeriousCreeper** [comment]
BTW, for now you can go to the Scripts folder in the modpack folder, open the betterwithmods.zs file in any text editor, and remove those two lines:

```
Cauldron.remove(<betterwithmods:material:6>);
Cauldron.remove(<betterwithmods:material:33>);
```

And that should fix your progression for now. Apparently CraftTweaker for 1.11.2 has been deleted from curse, so i need to wait for them to upload it again before i can submit my update.

**Comment by SilkenStrand** [comment]
Huh. Well that's odd. Wonder what's up. 

I was actually just going to ask about that. A script change so I could keep playing while waiting for the update, I mean? So thanks.

**Comment by SeriousCreeper** [comment]
Version 1.2 is on curse now, should fix thsi issue!
