### ISSUE TITLE
Water Canteen + Item Repairer

### ISSUE THREAD

**Issue by absolutedespair** [Kiyaku/SeriousRemnants#2]
Hello. There's a wrong interaction between "Item Repairer" perk(Player Stats 2) and Water Canteen(Tough as nails)
When you fill up your canteen your perk "repairs it" to Clean>Dirty>Empty state.
I know it's technically not a bug, but is there any way to fix this? I checked both mod configs myself and didn't find anything. Can you make water canteen an exception for "repairing" with tweaker/your own small mod? Or maybe something like a new water canteen, idk.
Also, if you want to see this for yourself note that this stat is a bit bugged and only certail levels work. (level 5 and level 10 confirmed)

**Comment by SeriousCreeper** [comment]
Hm that's not so great, i might report that to the devs of that mod, though they don't seem to be too active when it comes to changes, etc. Was a bit hesistant using this mod cause it barely has any configuration available. 

Might see if i can fix it with my own mod (and see how much effort it is). If not i may remove the mod (and possibly replace it with Levels, or something similar).
