### ISSUE TITLE
Ancient Trees

### ISSUE THREAD

**Issue by NeddieSeagoon** [Kiyaku/SeriousRemnants#4]
Ancient Trees loot packages don't break when you use them, allowing you to repeatedly click and get more loot.
Also the leaf blocks not only don't work with fast leaf decay, they don't decay AT ALL.

**Comment by SeriousCreeper** [comment]
They still don't crumble? I thought that was fixed (and i tried it, but don't think i tried it in the very latest version). Will look into it, thanks!

**Comment by NeddieSeagoon** [comment]
They SAY something like 'the package crumbles to dust', but it doesn't disappear :)

**Comment by SeriousCreeper** [comment]
Yep i know, i reported that to the mod dev a while ago and they fixed it, and it worked fine when i tested it few days ago (that version should be in 1.4.4 of the pack), but i think there was one or two more updates afterwards, wonder if they broke it again.
