### ISSUE TITLE
Crash when opening world

### ISSUE THREAD

**Issue by NeddieSeagoon** [Kiyaku/SeriousRemnants#5]
World was created with SR 1.4.2, when opening with 1.4.4 it crashes on entering the world.
[crash-2017-05-06_10.02.33-server.txt](https://github.com/Kiyaku/SeriousRemnants/files/980778/crash-2017-05-06_10.02.33-server.txt)

**Comment by SeriousCreeper** [comment]
Hm yeah i noticed that too in my LP world, kinda odd. Launching it the second time worked but it seems to have turned TurnTables (how ironic) into filtered hoppers. Not sure if i can do anything about it, but will report to BetterWithMods. Let me know if launching it again works.

**Comment by NeddieSeagoon** [comment]
Nope, still freezes. I let it sit for a while, hoping maybe it was just taking its time changing all those turntables into hoppers, but then I noticed that a crash report was generated right when I had opened the world.
FWIW when I opened the world the very first time there were a number of missing blocks, including some slabs from Rustic.

**Comment by SeriousCreeper** [comment]
Ah shoot. I might have to downgrade BetterWithMods again then. For me it seemed to have fixed itself when i opened it a 2nd time. Well glad we have AromaBackup! 
If you want, try to download the 1.4.3 version, and use the betterwithmods mod file and config file from that pack in the current version and load your backup from before you updated. Not ideal but a quick hotfix.

**Comment by NeddieSeagoon** [comment]
Okay, now it opens! 
But now a lot of textures are messed up, like these: 
<img width="596" alt="screen shot 2017-05-06 at 12 23 53 pm" src="https://cloud.githubusercontent.com/assets/17067128/25771629/2acfa606-3257-11e7-87a2-6c28055fe746.png">
<img width="1920" alt="screen shot 2017-05-06 at 12 24 59 pm" src="https://cloud.githubusercontent.com/assets/17067128/25771630/2ad3aaa8-3257-11e7-93e4-6ae6f2896248.png">
The leaves are actually missing now, and a lot of crops have blank textures too.

Also if it helps, this is the message I got when starting the world: 
<img width="1022" alt="screen shot 2017-05-06 at 12 22 38 pm" src="https://cloud.githubusercontent.com/assets/17067128/25771640/659989c8-3257-11e7-9f31-db29c8542e1d.png">
It was the same the first time I opened the world on 1.4.4

**Comment by SeriousCreeper** [comment]
That's really weird, especially the UI being funky, i didn't have those issues at all. Could you send me your pre-1.4.4 save file by any chance? Might help making the new update compatible with this. 

The missing blocks/items is fine, they renamed a bunch of things. That shouldn't cause any crazy texture issues though.

**Comment by NeddieSeagoon** [comment]
You bet!
It's 80MB though, how's best to send it to you?

**Comment by SeriousCreeper** [comment]
Perhaps DropBox? I think it gives you a lot of space now for the free account. Or google drive should have enough space too i think.

**Comment by NeddieSeagoon** [comment]
https://drive.google.com/open?id=0Bx54g_h1TrqoVXNFZm9JR3ZiaXM

:)

**Comment by SeriousCreeper** [comment]
Thanks!

Alright after messing with that for a bit, if i use the 1.4.4 pack version and downgrade BetterWithMods to 1.1.6 (and use the old config file, which i will include here below) i can load up your world just fine it seems. No weird texture issues or anything. 

Please give that a try, just override the config file with this one: https://dl.dropboxusercontent.com/u/1658875/Minecraft/betterwithmods.cfg

Reported the BetterWithMod bug with the new version to the dev. Will probably downgrade for now and upload a new pack version soon.

**Comment by NeddieSeagoon** [comment]
Woo! Seems all good, except that I'm still missing ToughAsNails, Survivalist, and Waystones textures (they're showing up blank with durability bars, as above).
