### ISSUE TITLE
Server Crash on Sleeping

### ISSUE THREAD

**Issue by Falnyx** [Kiyaku/SeriousRemnants#6]
Running a server on my own machine for a friend and I. When we tried to sleep the server crashed when we would have woken up, any time either of us tries to connect to the server after it is launched it crashes.

Here is the crash report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SHLoadingPlugin (ScalingHealth-1.11.x-1.0.5-47.jar)
  Default Options (DefaultOptions_1.11.2-8.2.2.jar)
  AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  FMLPlugin (InventoryTweaks-1.62+beta.84.jar)
  LoadingPlugin (NoNausea-MC1.11-1.0.jar)
  LoadingPlugin (Quark-r1.2-90.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.13.jar)
  llibrary (llibrary-1.7.4-1.11.2.jar)
  LoadingPlugin (ResourceLoader-MC1.11.2-1.5.2.jar)
  literalascension (literalascension-1.11.2-1.0.1.1.jar)
  IvToolkit (IvToolkit-1.3.2.1.jar)
  DummyPlugin (ForgeEndertech-1.11.2-2.0.8.0-build.0025.jar)
  LoadingPlugin (HardcoreDarkness-MC1.11.2-1.9.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  ForgelinPlugin (Forgelin-1.4.1.jar)
  TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 5/7/17 1:23 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75119_b(F)V
	at com.seriouscreeper.sradditions.events.handlers.SleepHandler.onWakeUp(SleepHandler.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_308_SleepHandler_onWakeUp_PlayerWakeUpEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerWakeup(ForgeEventFactory.java:479)
	at net.minecraft.entity.player.EntityPlayer.func_70999_a(EntityPlayer.java:1619)
	at net.minecraft.entity.player.EntityPlayerMP.func_70999_a(EntityPlayerMP.java:681)
	at net.minecraft.entity.player.EntityPlayerMP.func_71123_m(EntityPlayerMP.java:1011)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:794)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:451)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 485061824 bytes (462 MB) / 1990721536 bytes (1898 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xmx4G -XX:MaxPermSize=256M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 112 mods loaded, 112 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282-universal.jar) 
	UCHIJAAAA	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282-universal.jar) 
	UCHIJAAAA	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJAAAA	ivtoolkit{1.3.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	forgeendertech{1.11.2-2.0.8.0} [Forge Endertech] (ForgeEndertech-1.11.2-2.0.8.0-build.0025.jar) 
	UCHIJAAAA	adchimneys{1.11.2-2.0.7.0} [Advanced Chimneys] (AdChimneys-1.11.2-2.0.7.0-build.0025.jar) 
	UCHIJAAAA	animania{1.0.4.6} [Animania] (animania-1.11.2-1.0.4.6.jar) 
	UCHIJAAAA	applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar) 
	UCHIJAAAA	jei{4.3.1.260} [Just Enough Items] (jei_1.11.2-4.3.1.260.jar) 
	UCHIJAAAA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJAAAA	aquaculture{1.5.0} [Aquaculture] (Aquaculture-1.11.2-1.5.0.33.jar) 
	UCHIJAAAA	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJAAAA	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJAAAA	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHIJAAAA	atg{2} [Alternate Terrain Generation] (atg-1.11.2-2.0.1.jar) 
	UCHIJAAAA	theoneprobe{1.4.6} [The One Probe] (theoneprobe-1.1x-1.4.6.jar) 
	UCHIJAAAA	attaineddrops{2.3.1} [Attained Drops 2] (AttainedDrops-1.11.2-2.3.1.jar) 
	UCHIJAAAA	quark{r1.2-90} [Quark] (Quark-r1.2-90.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	betterwithmods{1.1.4} [Better With Mods] (Better With Mods-1.1.4-1.11.2.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
	UCHIJAAAA	betterquesting{2.4.226} [Better Questing] (BetterQuesting-2.4.226.jar) 
	UCHIJAAAA	bqt{0.9} [Better Questing Triggerer] (BetterQuestingTriggerer-0.9.jar) 
	UCHIJAAAA	betterthanmending{@VERSION@} [Better Than Mending] (BetterThanMending-1.0.0.jar) 
	UCHIJAAAA	biomesoplenty{6.0.2.2169} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2169-universal.jar) 
	UCHIJAAAA	blockdispenser{1.0} [BlockDispenser] (BlockDispenser-1.1-2.jar) 
	UCHIJAAAA	boosterrockets{1.0.2} [BoosterRockets] (BoosterRockets-1.11.2-1.1.0.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.2-1.11.2.jar) 
	UCHIJAAAA	charcoal_pit{1.2_1} [Charcoal Pit] (CharcoalPit-[1.11.2]-1.2_1.jar) 
	UCHIJAAAA	chesttransporter{2.7.5} [Chest Transporter] (ChestTransporter-1.11.2-2.7.5.jar) 
	UCHIJAAAA	chisel{MC1.11.2-0.0.9.13} [Chisel] (Chisel-MC1.11.2-0.0.9.13.jar) 
	UCHIJAAAA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJAAAA	one_point_twelve_concrete{v 1.0} [1.12 Concrete] (concreteMod-v1.0.jar) 
	UCHIJAAAA	cookingforblockheads{5.3.20} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.20.jar) 
	UCHIJAAAA	craftingtweaks{7.1.6} [Crafting Tweaks] (CraftingTweaks_1.11.2-7.1.6.jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCHIJAAAA	crafttweaker{3.0.24} [Crafttweaker] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCHIJAAAA	d3core{1.3.0.66} [D³Core] (D3Core-1.11.2-1.3.0.66.jar) 
	UCHIJAAAA	koresample{1.11.2-L1} [Kore Sample] (koresample-1.11.2.jar) 
	UCHIJAAAA	dendrology{1.11.2-L1.0.1} [Ancient Trees] (dendrology-1.11.2-L1.0.1.jar) 
	UCHIJAAAA	dirt2path{1.4.0} [Dirt2Path] (dirt2path-1.4.0.jar) 
	UCHIJAAAA	dldungeonsjdg{1.9.0} [Doomlike Dungeons] (DoomlikeDungeons-1.9.2-MC1.11.2.jar) 
	UCHIJAAAA	earthworks{1.2.1} [Earthworks] (Earthworks-1.11.2-1.2.1.jar) 
	UCHIJAAAA	embers{0.206} [Embers] (embers-0.206.jar) 
	UCHIJAAAA	enchiridion{3.1.17} [Enchiridion] (Enchiridion-1.11.2-3.1.17.jar) 
	UCHIJAAAA	fairylights{2.1.0} [Fairy Lights] (fairylights-2.1.0-1.11.2.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.1-anarchy.jar) 
	UCHIJAAAA	forgelin{1.4.1} [Forgelin] (Forgelin-1.4.1.jar) 
	UCHIJAAAA	grue{1.3.4} [Grue] (Grue-1.11.2-1.3.4.jar) 
	UCHIJAAAA	hardcoredarkness{1.9} [Hardcore Darkness] (HardcoreDarkness-MC1.11.2-1.9.jar) 
	UCHIJAAAA	harvest{1.11-1.2.0-12} [Harvest] (Harvest-1.11-1.2.0-12.jar) 
	UCHIJAAAA	hcmw{1.0} [Homecraft Mineware] (hcmw-1.11.2-0.2.9-universal.jar) 
	UCHIJAAAA	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCHIJAAAA	impstorage{1.4.1} [Impractical Storage] (ImpracticalStorage-1.4.1-MC1.11.2.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-2.0.1.jar) 
	UCHIJAAAA	initialinventory{2.0.1} [InitialInventory] (InitialInventory-2.0.1.jar) 
	UCHIJAAAA	inventorytweaks{1.62+beta.84.b3ecfb1} [Inventory Tweaks] (InventoryTweaks-1.62+beta.84.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJAAAA	jacb{1.0.6} [JACB] (JACB-1.11.2-1.0.6.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	levelup{${version}} [Level Up!] (LevelUp!-0.14.4-1.11.2.jar) 
	UCHIJAAAA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
	UCHIJAAAA	literalascension{1.11.2-1.0.1.1} [Literal Ascension] (literalascension-1.11.2-1.0.1.1.jar) 
	UCHIJAAAA	loottweaker{0.0.5.1} [LootTweaker] (LootTweaker-1.11.2-0.0.5.1.jar) 
	UCHIJAAAA	loreexpansion{1.11.2-1.1.5-10} [Lore Expansion] (LoreExpansion-1.11.2-1.1.5-10.jar) 
	UCHIJAAAA	lumberjack{1.0} [lumberjack] (Lumberjack-1.11.2-1.3.1.48.jar) 
	UCHIJAAAA	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCHIJAAAA	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCHIJAAAA	minicoal{1.0} [MiniCoal] (minicoal-1.11.2-1.0.jar) 
	UCHIJAAAA	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass-1.11.2-1.3.0.jar) 
	UCHIJAAAA	nonausea{1.0} [NoNausea] (NoNausea-MC1.11-1.0.jar) 
	UCHIJAAAA	oreexcavation{1.3.85} [OreExcavation] (OreExcavation-1.3.85.jar) 
	UCHIJAAAA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2g.jar) 
	UCHIJAAAA	parachutemod{1.6.2} [Parachute Mod] (parachutemod-ng-1.11.2-1.6.2-426.jar) 
	UCHIJAAAA	shetiphiancore{3.4.4} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.4.jar) 
	UCHIJAAAA	platforms{1.3.4} [Platforms] (platforms-1.11.0-1.3.4.jar) 
	UCHIJAAAA	progenitor{0.0.3+1.11} [Progenitor] (progenitor-0.0.3+1.11.jar) 
	UCHIJAAAA	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCHIJAAAA	reccomplex{1.2.10} [Recurrent Complex] (RecurrentComplex-1.2.10.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCHIJAAAA	roots{0.014} [Roots 2] (roots-2-0.014.jar) 
	UCHIJAAAA	ropebridge{2.0.5} [Rope Bridge] (ropebridge-1.11.2-2.0.5.jar) 
	UCHIJAAAA	roughmobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.11.2.jar) 
	UCHIJAAAA	rustic{0.1.2.2} [Rustic] (rustic-0.1.2.2.jar) 
	UCHIJAAAA	silentlib{2.1.0} [Silent Lib] (SilentLib-1.11.x-2.1.0-53.jar) 
	UCHIJAAAA	scalinghealth{1.0.5} [Scaling Health] (ScalingHealth-1.11.x-1.0.5-47.jar) 
	UCHIJAAAA	spartanshields{1.3} [Spartan Shields] (SpartanShields-1.11.2-1.3a.jar) 
	UCHIJAAAA	spiceoflife{1.3.8} [The Spice of Life] (SpiceOfLife-mc1.11.2-1.3.8.jar) 
	UCHIJAAAA	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.5.jar) 
	UCHIJAAAA	sradditions{0.1.9} [SeriousCreepers SR Additions] (sradditions-0.1.9.jar) 
	UCHIJAAAA	bq_standard{2.4.132} [Standard Expansion] (StandardExpansion-2.4.132.jar) 
	UCHIJAAAA	stg{1.11.2-1.1.1} [SwingThroughGrass] (stg-1.11.2-1.1.1.jar) 
	UCHIJAAAA	storageboats{1.6} [Storage Boats Mod] (StorageBoats-1.9.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.2.2} [Storage Drawers] (StorageDrawers-1.11.2-4.2.2.jar) 
	UCHIJAAAA	supercraftingframe{1.2.1.89} [Super Crafting Frame] (supercraftingframe-1.11-1.2.1.89.jar) 
	UCHIJAAAA	survivalist{1.8.5} [Survivalist] (Survivalist-1.11.2-1.8.5.jar) 
	UCHIJAAAA	torchmaster{1.0} [TorchMaster] (torchmaster_1.11.2-1.2.1.24.jar) 
	UCHIJAAAA	trashslot{7.4.3} [TrashSlot] (TrashSlot_1.11.2-7.4.3.jar) 
	UCHIJAAAA	vc{4.26.13} [ViesCraft] (ViesCraft-1.11.2-4.26.13.jar) 
	UCHIJAAAA	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCHIJAAAA	visiblearmorslots{3.1.1} [Visible Armor Slots] (VisibleArmorSlots[1.11.2]-3.1.1.jar) 
	UCHIJAAAA	waystones{3.0.13} [Waystones] (Waystones_1.11.2-3.0.13.jar) 
	UCHIJAAAA	weaponcaseloot{5.0.3-beta} [WeaponCaseLoot] (weaponcaseloot-1.11.2-5.0.3-beta.jar) 
	UCHIJAAAA	wearablebackpacks{2.3.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.3.0.jar) 
	UCHIJAAAA	weirdinggadget{1.0} [The Weirding Gadget] (weirdinggadget-1.11.2-0.1.7-universal.jar) 
	UCHIJAAAA	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.3.6.jar) 
	UCHIJAAAA	xpbook{0.0.2-beta} [XPBook] (xpbook-1.11.2-0.0.2-beta.jar) 
	Loaded coremods (and transformers): 
SHLoadingPlugin (ScalingHealth-1.11.x-1.0.5-47.jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
Default Options (DefaultOptions_1.11.2-8.2.2.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
FMLPlugin (InventoryTweaks-1.62+beta.84.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (NoNausea-MC1.11-1.0.jar)
  lumien.nonausea.asm.ClassTransformer
LoadingPlugin (Quark-r1.2-90.jar)
  vazkii.quark.base.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  shetiphian.core.asm.ClassTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.13.jar)
  team.chisel.common.asm.ChiselTransformer
llibrary (llibrary-1.7.4-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (ResourceLoader-MC1.11.2-1.5.2.jar)
  lumien.resourceloader.asm.ClassTransformer
literalascension (literalascension-1.11.2-1.0.1.1.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
IvToolkit (IvToolkit-1.3.2.1.jar)
  
DummyPlugin (ForgeEndertech-1.11.2-2.0.8.0-build.0025.jar)
  
LoadingPlugin (HardcoreDarkness-MC1.11.2-1.9.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ForgelinPlugin (Forgelin-1.4.1.jar)
  
TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	d3core: Debug: false Silliness: false AprilFools: false PastPost:true
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

It seems like the issue is the way you handled taking hunger away from the player when they woke up

**Comment by SeriousCreeper** [comment]
Thanks!
Just uploaded version 0.2.3 of SR Additions. Feel free to manually update your server and client (every player has to do that), and it should work again.
